name: lint

on: [push, pull_request]

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: checkout submodules
      run: git submodule update --init --recursive
    - uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: pip
      run: pip install -r requirements_core.txt
    - run: pyright
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: checkout submodules
      run: git submodule update --init --recursive
    - uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: pip
      run: pip install -r requirements_linting.txt
    - name: black
      run: black --check .
    - name: isort
      run: isort --check .
